import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex-col justify-between items-center p-24 min-h-screen">
        <div className="flex justify-between items-center text-sm max-w-6xl w-full z-index z-20 font-sans gap-2">
          <p className='border rounded-xl border-neutral-800 p-3 font-mono'>
            Get started by editing&nbsp;
            <code className="font-bold font-sans">pages/index.js</code>
          </p>
          <div>
            <a
              className='flex'
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className="invert"
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className="flex justify-center items-center relative p-32">
          <Image
            className="relative invert"
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div 
            className=''
            width={180}
            height={37}
          />
        </div>

        <div className="grid grid-cols-4 max-w-full gap-2">
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="py-4 px-5 rounded-xl bg-transparent transition delay-200 bg-neutral-400 hover:border border-neutral-700 group"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`font-sans font-semibold text-2xl ${inter.className}`}>
              Docs <span className="inline-block transition-transform group-hover:translate-x-1">-&gt;</span>
            </h2>
            <p className={`font-sans font-light text-sm text-neutral-400 mt-2 ${inter.className}`}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="py-4 px-5 rounded-xl bg-transparent transition delay-200 bg-neutral-400 hover:border border-neutral-700 group"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`font-sans font-semibold text-2xl ${inter.className}`}>
              Learn <span className="inline-block transition-transform group-hover:translate-x-1">-&gt;</span>
            </h2>
            <p className={`font-sans font-light text-sm text-neutral-400 mt-2 ${inter.className}`}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="py-4 px-5 rounded-xl bg-transparent transition delay-200 bg-neutral-400 hover:border border-neutral-700 group"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`font-sans font-semibold text-2xl ${inter.className}`}>
              Templates <span className="inline-block transition-transform group-hover:translate-x-1">-&gt;</span>
            </h2>
            <p className={`font-sans font-light text-sm text-neutral-400 mt-2 ${inter.className}`}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="py-4 px-5 rounded-xl bg-transparent transition delay-200 bg-neutral-400 hover:border border-neutral-700 group"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`font-sans font-semibold text-2xl ${inter.className}`}>
              Deploy <span className="inline-block transition-transform group-hover:translate-x-1">-&gt;</span>
            </h2>
            <p className={`font-sans font-light text-sm text-neutral-400 mt-2 ${inter.className}`}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
